ARG ros_distro="humble"

FROM --platform=amd64 osrf/ros:${ros_distro}-desktop-full
ARG UID=1000
ARG GID=1000
ENV DEBIAN_FRONTEND=noninteractive

ADD ./docker/install_tools.sh /scripts/install_tools.sh
RUN rm -rf /var/lib/apt/lists/* && apt update && apt install -y libarchive-dev && /scripts/install_tools.sh

ADD ./docker/install_rosdeps.sh /scripts/install_rosdeps.sh
RUN rm -rf /var/lib/apt/lists/* && apt update && apt upgrade -y && /scripts/install_rosdeps.sh

# Install robotnik-controllers
COPY ./src/academy_robot_simulation/debs/*.deb /tmp/debs/
ADD ./docker/install_third_parties.sh /scripts/install_third_parties.sh
RUN rm -rf /var/lib/apt/lists/* && apt update && /scripts/install_third_parties.sh

RUN groupadd -g "${GID}" user \
  && useradd --create-home --no-log-init -u "${UID}" -g "${GID}" user
RUN chown -R user:user /tmp
RUN apt-get update && apt-get install -y acl

USER user

ENV HISTFILE="/home/user/.vscode-server/.bash_history"
ENV RCUTILS_COLORIZED_OUTPUT=1
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ENV GZ_SIM_SYSTEM_PLUGIN_PATH=/opt/ros/${ros_distro}/lib
ENV LD_LIBRARY_PATH=/opt/ros/${ros_distro}/lib
RUN echo "PS1='\[\033[01;33m\][humble-dev-x86] ${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '" >> /home/user/.bashrc
RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/user/.bashrc
RUN echo "if [ -f \"/home/user/ros2_ws/install/setup.bash\" ]; then source /home/user/ros2_ws/install/setup.bash; fi" >> /home/user/.bashrc

WORKDIR /home/user/ros2_ws/

# Add Entrypoint
CMD [ "/bin/bash" ]