apt-get install -y ros-humble-rmw-cyclonedds-cpp
apt-get install -y ros-humble-rmw-dds-common
apt-get install -y ros-humble-actionlib-msgs
apt-get install -y ros-humble-control-msgs
apt-get install -y ros-humble-example-interfaces
apt-get install -y ros-humble-ros-gz
apt-get install -y ros-humble-gz-ros2-control
apt-get install -y ros-humble-sdl2-vendor
apt-get install -y ros-humble-joint-state-publisher-gui
apt-get install -y ros-humble-robot-state-publisher
apt-get install -y ros-humble-controller-manager
apt-get install -y ros-humble-ros2-control
apt-get install -y ros-humble-ros2-controllers
apt-get install -y ros-humble-rqt-joint-trajectory-controller
apt-get install -y ros-humble-joint-trajectory-controller
apt-get install -y ros-humble-joint-state-broadcaster
apt-get install -y ros-humble-moveit